apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-spring-cloud-gcp
  labels:
    app: contact-spring-cloud-gcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contact-spring-cloud-gcp
  template:
    metadata:
      labels:
        app: contact-spring-cloud-gcp
    spec:
      containers:
      - name: contact-spring-cloud-gcp
        imagePullPolicy: Always
        image: us-central1-docker.pkg.dev/m2c-demo/container/contact-spring-cloud-gcp:latest
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /contact-api.json
        - name: GOOGLE_CLOUD_PROJECT
          value: m2c-demo
        envFrom:
        - configMapRef:
            name: db-cm
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"

---
apiVersion: v1
kind: Service
metadata:
  name: contact-spring-cloud-gcp
spec:
  selector:
    app: contact-spring-cloud-gcp
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    name: web
